version: "3.7"
services:
  garage:
    restart: always
    build: 
      context: containers/garage
      args:
        USER: "tsukasa"
        RUBY_VER: "2.6.1"
    ports:
      - "3000:3000"
    volumes:
      - ./data/garage:/home/tsukasa/develop
    tty: true
