version: "3.7"
services:

  garage:
    restart: always
    build:
      context: containers/garage
      args:
        USER: ${USER}
        RUBY_VER: "2.7.1"
        NODE_VER: "12.16.2"
        PYTHON_VER: "3.8.2"
        GO_VER: "1.14.2"
        GIT_USER: "Tsukasa OISHI"
        GIT_MAILADDRESS: "tsukasa.oishi@gmail.com"
    ports:
      - "3000:3000"
    volumes:
      - ./data/garage/develop:/home/${USER}/develop:cached
      - ./data/garage/.ssh:/home/${USER}/.ssh:cached
      - ./data/garage/.config:/home/${USER}/.config:cached
    tty: true

  percona-db:
    restart: always
    image: percona:8
    volumes:
      - ./data/percona-db:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""

  percona-db-replica:
    restart: always
    image: percona:8
    volumes:
      - ./data/percona-db-replica:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""

  postgres-db:
    restart: always
    image: postgres:11
    volumes:
      - ./data/postgres-db:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: "tsukasa"
      POSTGRES_PASSWORD: ""

  memcached:
    restart: always
    image: memcached:1.5

  redis:
    restart: always
    image: redis:5.0

  httpd:
    image: httpd:latest
